routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'DashboardController@index')
    ->name('dashboard');

Auth::routes(['register' => false]);

Route::get('products/{id}/gallery', 'ProductController@gallery')
    ->name('products.gallery');
Route::resource('products', 'ProductController');

Route::resource('product-galleries', 'ProductGalleryController');

Route::get('transactions/{id}/set-status', 'TransactionController@setStatus')
    ->name('transactions.status');

Route::resource('transactions', 'TransactionController');

app/Models/ProductGallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ProductGallery extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'products_id', 'photo', 'is_default'
    ];

    protected $hidden = [];

    public function product()
    {
        return $this->belongsTo(Product::class, 'products_id', 'id');
    }

    public function getPhotoAttribute($value)
    {
        return url('storage/' . $value);
    }
}

app/Http/Controllers/ProductGalleryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\ProductGallery;
use App\Models\Product;
use App\Http\Requests\ProductGalleryRequest;

class ProductGalleryController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = ProductGallery::with(['product'])->get();
        return view('pages.product-galleries.index', [
            'items' => $items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product = Product::all();
        return view('pages.product-galleries.create', [
            'product' => $product
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductGalleryRequest $request)
    {
        $data = $request->all();
        $data['photo'] = $request->file('photo')->store(
            'assets/gallery',
            'public'
        );

        ProductGallery::create($data);
        return redirect()->route('product-galleries.index')->with('sukses', 'Gambar produk berhasil ditambahkan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = ProductGallery::findOrFail($id);
        $item->delete();

        return redirect()->route('product-galleries.index')->with('hapus', 'Gambar produk berhasil dihapus');
    }
}

resources/views/pages/product-galleries/create.blade.php
@extends('layouts.default')

@section('content')
    <div class="container">
        <div class="card-shadow">
            <div class="card-header">
                <strong>Tambah Barang</strong>
            </div>
            <div class="card-body card-block">
                <form action="{{route('product-galleries.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="products_id">Nama Barang</label>
                        <select name="products_id" class="form-control @error('products_id') is-invalid @enderror" required>
                            <option value="">Pilih Barang</option>
                            @foreach ($product as $item)
                                <option value="{{$item->id}}">{{$item->name}}</option>
                            @endforeach
                        </select>
                        @error('name') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="photo">Tipe Barang</label><br>
                        <input type="file" name="photo" class=" @error('photo') is-invalid @enderror" value="{{old('photo')}}" accept="image/*" required>
                        @error('photo') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                   <div class="form-group">
                       <label for="is_default">Jadikan Default</label>
                        <br>
                        <label>
                            <input type="radio" name="is_default" class="form-control @error('is_default') is-invalid @enderror" value="1"/> Ya
                        </label>
                        &nbsp;
                        <label>
                            <input type="radio" name="is_default" class="form-control @error('is_default') is-invalid @enderror" value="0"/> No
                        </label>
                        @error('is_default') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <button class="btn btn-primary btn-block">
                        Tambah Foto Barang
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/product-galleries/index.blade.php
@extends('layouts.default')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
                @if (session('sukses'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <i class="fa fa-check-circle"></i> 
                    {{session('sukses')}}
                </div>
                @endif
                @if (session('hapus'))
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <i class="fa fa-check-circle"></i> 
                    {{session('hapus')}}
                </div>
                @endif
                <div class="card-body">
                    <h4 class="box-title">Daftar Barang</h4>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama Barang</th>
                                    <th>Foto</th>
                                    <th>Default</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $no= 1 ?>
                               @forelse ($items as $item)
                               <tr>
                                <td>{{$no}}</td>
                                <td>{{$item->product->name}}</td>
                                <td>
                                    <img src="{{url($item->photo)}}" alt="">    
                                </td>
                                <td>{{$item->is_default ? 'Ya' : 'Tidak'}}</td>
                                <td>
                                    <form action="{{route('product-galleries.destroy', $item->id)}}" method="POST" class="d-inline" onclick="return confirm('yakin produk ingin dihapus?') ">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                    </form>
                                </td>
                                <?php $no++?>
                            </tr>
                               @empty
                                   <tr>
                                       <td colspan="6" class="text-center">
                                           Data Product Kosong
                                       </td>
                                   </tr>
                               @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection