routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'DashboardController@index')
    ->name('dashboard');

Auth::routes(['register' => false]);

Route::get('products/{id}/gallery', 'ProductController@gallery')
    ->name('products.gallery');
Route::resource('products', 'ProductController');

Route::resource('product-galleries', 'ProductGalleryController');

Route::get('transactions/{id}/set-status', 'TransactionController@setStatus')
    ->name('transactions.status');

Route::resource('transactions', 'TransactionController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Transaction;


use Illuminate\Http\Request;

class TransactionController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Transaction::all();

        return view('pages.transactions.index')->with([
            'items' => $items
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = Transaction::with('details.product')->findOrFail($id);

        return view('pages.transactions.show')->with([
            'item' => $item
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Transaction::findOrFail($id);

        return view('pages.transactions.edit')->with([
            'item' => $item
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $item = Transaction::findOrFail($id);
        $item->update($data);

        return redirect()->route('transactions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Transaction::findOrFail($id);
        $item->delete();

        return redirect()->route('transactions.index');
    }

    public function setStatus(Request $request, $id)
    {
        $request->validate([
            'status' => 'required|in:PENDING,SUCCESS,FAILED'
        ]);

        $item = Transaction::findOrFail($id);
        $item->transaction_status = $request->status;
        $item->save();

        return redirect()->route('transactions.index');
    }
}

resources/views/pages/transactions/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="container">
        <div class="card-shadow">
            <div class="card-header">
                <strong>Tambah Barang</strong>
            </div>
            <div class="card-body card-block">
                <form action="{{route('transactions.update', $item->id)}}" method="POST">
                    @method('PUT')
                    @csrf
                    <div class="form-group">
                        <label for="name">Nama Barang</label>
                        <input type="text" name="name" class="form-control @error('name') is-invalid @enderror" value="{{$item->name}}">
                        @error('name') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" name="email" class="form-control @error('email') is-invalid @enderror" value="{{$item->email}}">
                        @error('email') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="number">Nomor Telp</label>
                        <input type="text" name="number" class="form-control @error('number') is-invalid @enderror" value="{{$item->number}}">
                        @error('number') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <div class="form-group">
                        <label for="address">Jumlah Barang</label>
                        <input type="text" name="address" class="form-control @error('address') is-invalid @enderror" value="{{$item->address}}">
                        @error('address') <div class="text-muted">{{$message}}</div> @enderror
                    </div>
                    <button class="btn btn-primary btn-block">
                        Tambah Barang
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/transactions/index.blade.php
@extends('layouts.default')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card">
               <div class="card-body">
                    <h4 class="box-title">Daftar Transaksi</h4>
                </div>
                <div class="card-body--">
                    <div class="table-stats order-table ov-h">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Nomor</th>
                                    <th>Alamat</th>
                                    <th>Total Transaksi</th>
                                    <th>Status</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $no=1 ?>
                               @forelse ($items as $item)
                               <tr>
                                <td>{{$no}}</td>
                                <td>{{$item->name}}</td>
                                <td>{{$item->email}}</td>
                                <td>{{$item->number}}</td>
                                <td>{{$item->address}}</td>
                                <td>{{$item->transaction_total}}</td>
                                <td>
                                    @if ($item->transaction_status == 'PENDING')
                                        <span class="badge badge-warning">
                                        @elseif($item->transaction_status == 'SUCCESS')
                                        <span class="badge badge-success">
                                        @elseif($item->transaction_status == 'FAILED')
                                        <span class="badge badge-danger">
                                        @else
                                        <span>
                                    @endif   
                                        {{$item->transaction_status}}
                                        </span>
                                </td>
                                <td>
                                    @if ($item->transaction_status == 'PENDING')
                                    <a href="{{route('transactions.status', $item->id)}}?status=SUCCESS" class="btn btn-success btn-sm">
                                        <i class="fa fa-check"></i>
                                    </a> 
                                    <a href="{{route('transactions.status', $item->id)}}?status=FAILED" class="btn btn-danger btn-sm">
                                        <i class="fa fa-times"></i>
                                    </a>
                                    @endif
                                    <a href="#mymodal"
                                    data-remote = "{{route('transactions.show', $item->id)}}"
                                    data-toggle = "modal"
                                    data-target = "#mymodal"
                                    data-title = "Detail Transaksi {{$item->uuid}} " 
                                    class="btn btn-success btn-sm">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="{{route('transactions.edit', $item->id)}}" class="btn btn-success btn-sm">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    <form action="{{route('transactions.destroy', $item->id)}}" method="POST" class="d-inline" onclick="return confirm('yakin produk ingin dihapus?') ">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-danger btn-sm">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                    </form>
                                </td>
                                <?php $no++?>
                            </tr>
                               @empty
                                   <tr>
                                       <td colspan="7" class="text-center">
                                           Data Product Kosong
                                       </td>
                                   </tr>
                               @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/transactions/show.blade.php
<table class="table table-bordered">
    <tr>
        <th>Nama</th>
        <td>{{$item->name}}</td>
    </tr>
    <tr>
        <th>Email</th>
        <td>{{$item->email}}</td>
    </tr>
    <tr>
        <th>No Telp</th>
        <td>{{$item->number}}</td>
    </tr>
    <tr>
        <th>Alamat</th>
        <td>{{$item->address}}</td>
    </tr>
    <tr>
        <th>Total Transaksi</th>
        <td>{{$item->transaction_total}}</td>
    </tr>
    <tr>
        <th>Status</th>
        <td>{{$item->transaction_status}}</td>
    </tr>
    <tr>
        <th>Data Pembelian</th>
        <td>
            <table class="table table-bordered w-100">
                <tr>
                    <th>Nama Barang</th>
                    <th>Tipe Barang</th>
                    <th>Harga</th>
                </tr>
               @foreach ($item->details as $detail)
                   <tr>
                       <td>{{$detail->product->name}}</td>
                       <td>{{$detail->product->type}}</td>
                       <td>{{$detail->product->price}}</td>
                   </tr>
               @endforeach
            </table>
        </td>
    </tr>
</table>

<div class="row">
    <div class="col-4">
      <a href="{{ route('transactions.status', $item->id) }}?status=SUCCESS" class="btn btn-success btn-block">
        <i class="fa fa-check"></i> Set Sukses
      </a>
    </div>
    <div class="col-4">
      <a href="{{ route('transactions.status', $item->id) }}?status=FAILED" class="btn btn-danger btn-block">
        <i class="fa fa-times"></i> Set Gagal
      </a>
    </div>
    <div class="col-4">
      <a href="{{ route('transactions.status', $item->id) }}?status=PENDING" class="btn btn-warning btn-block">
        <i class="fa fa-spinner"></i> Set Pending
      </a>
    </div>
  </div>